### ISSUE TITLE
Bug : Material-UI: the `anchorEl` prop provided to the component is invalid.

### ISSUE THREAD

**Issue by mikbry** [mikbry/material-ui-color-components#20]
On Firefox:
The anchor element should be part of the document layout.
Make sure the element is present in the document or that it's not display none.
Error on Chrome:
checkPropTypes.js:20 Warning: Failed prop type: Material-UI: the `anchorEl` prop provided to the component is invalid.
The anchor element should be part of the document layout.
Make sure the element is present in the document or that it's not display none.
    in ForwardRef(Popover) (created by WithStyles(ForwardRef(Popover)))
    in WithStyles(ForwardRef(Popover)) (created by ColorPicker)
    in div (created by ColorPicker)
    in ColorPicker (created by Uncontrolled)
    in Uncontrolled
    in Unknown
    in ThemeProvider (created by ThemeProvider)
    in ThemeProvider (created by ThemeProvider)
    in StylesProvider (created by ThemeProvider)

**Comment by sherinshaju** [comment]
check this it will help you - https://codesandbox.io/s/use-ref-for-anchorel-forked-1pvh1

**Comment by mikbry** [comment]
Thanks @sherinshaju but it should be fixed ;-)

**Comment by Noumanijaz1** [comment]
Hello ANy on ehelp me out plx when I am logout my application thats show me above error and display menu or popover

**Comment by vinicius-gregorio** [comment]
> check this it will help you - https://codesandbox.io/s/use-ref-for-anchorel-forked-1pvh1

I cant get the code, facing the same issue.

**Comment by vedant-Dscission** [comment]
facing the same issue , anyone got the code

**Comment by heller-91** [comment]
> check this it will help you - https://codesandbox.io/s/use-ref-for-anchorel-forked-1pvh1

facing the same issue, sandbox is not opening

**Comment by sepkey** [comment]
facing the same issue, is there any way to fix it?

**Comment by asadullakkh** [comment]
facing the same issue, how did you guys fix it ?
